### ISSUE TITLE
CSS currentColor 属性值

### ISSUE THREAD

**Issue by tcatche** [tcatche/tcatche.github.io#120]
**本文博客地址：[CSS currentColor 属性值](http://tcatche.site/2021/02/css_current_color/).**

`currentColor` 关键字表示**当前元素设置的**或者**继承来的** color 属性的颜色值，可以用到任意**属性值为颜色**的地方。

这样说有点抽象，下面直接看几个例子，本文所有示例都在文章末尾：

## currentColor 可以设置为颜色的属性值

下面是一个设置边框，阴影颜色和文字颜色一样的例子：

```css
.example1 {
  color: red;
  border: 1px solid currentColor;
}

.example2 {
  color: red;
  box-shadow: 0 0 2px currentColor;
}
```

## currentColor 也可以使用到伪类和伪元素

如下，`currentColor` 对于伪元素也生效：

```css
.example3 {
  color: red;
}

.example3::after {
  content: '';
  display: inline-block;
  border: 4px solid transparent;
  border-left-color: currentColor
}
```

结合其他伪类，可以很方便的设置一些特殊的效果，比如下面是 .example3 的三角形随着 `hover` 状态改变的例子：

```css
/* 使用了 currentColor */
.example3:hover {
  color: green;
}

/* 不使用 currentColor */
.example3:hover {
  color: green;
}

.example3:hover::after {
  border-left-color: green;
}
```

从上面例子可以看出，使用 `currentColor` 代码精简了很多，特别是党当还有更多的伪类如 `:hover`、 `:visited`、 `:focus`、 `:active` 等存在时，可以节省更多的重复代码。

上述示例在线代码：

<p class="codepen" data-height="265" data-theme-id="dark" data-default-tab="css,result" data-user="tcatche" data-slug-hash="OJbyaxM" style="height: 265px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;" data-pen-title="OJbyaxM">
  <span>See the Pen <a href="https://codepen.io/tcatche/pen/OJbyaxM">
  OJbyaxM</a> by tcatche (<a href="https://codepen.io/tcatche">@tcatche</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://cpwebassets.codepen.io/assets/embed/ei.js"></script>

## caniuse
- [caniuse currentColor](https://caniuse.com/?search=currentColor)

基本上主流浏览器都支持了这个属性，可以放心使用。
