### ISSUE TITLE
各大浏览器CSSHack收集

### ISSUE THREAD

**Issue by tcatche** [tcatche/tcatche.github.io#3]
**本文博客地址：[各大浏览器CSSHack收集](http://tcatche.site/2016/03/各大浏览器CSSHack收集/).**

所谓的Hack就是只有特定浏览器才能识别这段hack代码。Hack 不是什么好东西，除非没有办法，我们尽量还是不要用着玩意。 下面是各个浏览器的CSS Hack 列表。

**Firefox 浏览器**

```css
@-moz-document url-prefix() {
  .selector {
    property: value;
  }
}
```

**支持所有Gecko内核的浏览器 (包括Firefox)**

```css
*>.selector {
	property: value;
}
```

**Webkit 内核浏览器**

```css
@media screen and (-webkit-min-device-pixel-ratio: 0) {
  Selector {
    property: value;
  }
}
```

**Opera 浏览器**

```css
html:first-child>body Selector {property:value;}
```

IE 浏览器针对不同的版本有不同个Hack方式。

**IE 9**

```css
:root Selector {property: value\9;}
```

**IE 9-**

```css
Selector {property: value\9;}
```

**IE 8**

```css
Selector {property: value/;}
或：
@media \0screen {
    Selector {property: value;}
}
```

**IE 8+**

```css
Selector {property: value\0;}
```

**IE 7**

```css
*+html Selector{property:value;}
或：
*:first-child+html Selector {property:value;}
```

**IE 7-**

```css
Selector {*property: value;}
```

**IE6**

```css
Selector {
  _property: value;
}
或：
*html Selector {
  property: value;
}
```

转自：[http://www.codeceo.com/article/css-hack.html](http://www.codeceo.com/article/css-hack.html)，侵删
